[package]
authors = ["Anton Kalinin <hurricanebox@gmail.com>"]
edition = "2018"
name = "jungle"
version = "0.1.0"

[[bin]]
name = "jungle"

[dependencies]
argh = "0.1"
bevy = {git = "https://github.com/bevyengine/bevy"}
tiled = "0.9.3"
